import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import '../../app/globals.css';
import Providers from '../providers';
import Sidebar from '@/domains/admin/auth/components/Sidebar';
import { HomeIcon, CalendarIcon, UsersIcon, FileText } from 'lucide-react';
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'SMG Cup Championship',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <Providers>
          <Sidebar
            items={[
              {
                title: 'Dashboard',
                url: '/admin',
                icon: <HomeIcon />,
              },
              {
                title: 'News',
                url: '/admin/news',
                icon: <FileText />,
              },
              {
                title: 'Matches',
                url: '/admin/matches',
                icon: <CalendarIcon />,
              },
              {
                title: 'Teams & Players',
                url: '/admin/teams',
                icon: <UsersIcon />,
              },
            ]}
          />
          <main className="lg:ml-64 min-h-screen">
            <div className="pt-16 lg:pt-0 px-4 lg:px-6 py-6">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
