import * as Types from '../../generated/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetMyFantasyTeamQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetMyFantasyTeamQuery = { __typename?: 'Query', myFantasyTeam?: { __typename?: 'FantasyTeam', id: string, teamName: string, budget: number, freeTransfers: number, captainPlayer: { __typename?: 'FantasyPlayer', playerId: string }, slots: Array<{ __typename?: 'FantasyTeamSlot', id: string, isBenched: boolean, slotOrder: number, fantasyPlayer: { __typename?: 'FantasyPlayer', playerId: string, displayName?: string | null, price: number, player: { __typename?: 'Player', id: string, firstName: string, lastName: string, position: Types.PlayerPosition, celebrationImageUrl?: string | null, team: { __typename?: 'Team', name: string } } } }> } | null };


export const GetMyFantasyTeamDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetMyFantasyTeam"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"myFantasyTeam"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"teamName"}},{"kind":"Field","name":{"kind":"Name","value":"budget"}},{"kind":"Field","name":{"kind":"Name","value":"freeTransfers"}},{"kind":"Field","name":{"kind":"Name","value":"captainPlayer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"playerId"}}]}},{"kind":"Field","name":{"kind":"Name","value":"slots"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isBenched"}},{"kind":"Field","name":{"kind":"Name","value":"slotOrder"}},{"kind":"Field","name":{"kind":"Name","value":"fantasyPlayer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"playerId"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"}},{"kind":"Field","name":{"kind":"Name","value":"price"}},{"kind":"Field","name":{"kind":"Name","value":"player"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"position"}},{"kind":"Field","name":{"kind":"Name","value":"celebrationImageUrl"}},{"kind":"Field","name":{"kind":"Name","value":"team"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]}}]}}]}}]}}]} as unknown as DocumentNode<GetMyFantasyTeamQuery, GetMyFantasyTeamQueryVariables>;