import * as Types from '../../generated/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type PlayerByIdQueryVariables = Types.Exact<{
  id: Types.Scalars['String']['input'];
}>;


export type PlayerByIdQuery = { __typename?: 'Query', playerById: { __typename?: 'Player', id: string, firstName: string, lastName: string, height: number, weight: number, imageUrl?: string | null, preferredFoot: Types.PreferredFoot, position: Types.PlayerPosition, dateOfBirth: string, age: number, team: { __typename?: 'Team', id: string, name: string }, stats: { __typename?: 'Stats', goals: number, assists: number, yellowCards: number, redCards: number, ownGoals: number, penaltiesMissed: number, penaltiesScored: number, goalkeeperSaves: number } } };


export const PlayerByIdDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PlayerById"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"playerById"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"height"}},{"kind":"Field","name":{"kind":"Name","value":"weight"}},{"kind":"Field","name":{"kind":"Name","value":"imageUrl"}},{"kind":"Field","name":{"kind":"Name","value":"preferredFoot"}},{"kind":"Field","name":{"kind":"Name","value":"position"}},{"kind":"Field","name":{"kind":"Name","value":"dateOfBirth"}},{"kind":"Field","name":{"kind":"Name","value":"age"}},{"kind":"Field","name":{"kind":"Name","value":"team"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"stats"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"goals"}},{"kind":"Field","name":{"kind":"Name","value":"assists"}},{"kind":"Field","name":{"kind":"Name","value":"yellowCards"}},{"kind":"Field","name":{"kind":"Name","value":"redCards"}},{"kind":"Field","name":{"kind":"Name","value":"ownGoals"}},{"kind":"Field","name":{"kind":"Name","value":"penaltiesMissed"}},{"kind":"Field","name":{"kind":"Name","value":"penaltiesScored"}},{"kind":"Field","name":{"kind":"Name","value":"goalkeeperSaves"}}]}}]}}]}}]} as unknown as DocumentNode<PlayerByIdQuery, PlayerByIdQueryVariables>;