import * as Types from '../../generated/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type MyPredictionsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type MyPredictionsQuery = { __typename?: 'Query', myPredictions: Array<{ __typename?: 'Prediction', id: string, predictedScore1: number, predictedScore2: number, isBoosted: boolean, createdAt: string, updatedAt: string, pointsEarned?: number | null, match: { __typename?: 'Match', id: string, date?: string | null, status: Types.MatchStatus, score1?: number | null, score2?: number | null, round: number, location?: Types.MatchLocation | null, firstOpponent: { __typename?: 'Team', id: string, name: string }, secondOpponent: { __typename?: 'Team', id: string, name: string } } }> };


export const MyPredictionsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"MyPredictions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"myPredictions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"predictedScore1"}},{"kind":"Field","name":{"kind":"Name","value":"predictedScore2"}},{"kind":"Field","name":{"kind":"Name","value":"isBoosted"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"pointsEarned"}},{"kind":"Field","name":{"kind":"Name","value":"match"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"score1"}},{"kind":"Field","name":{"kind":"Name","value":"score2"}},{"kind":"Field","name":{"kind":"Name","value":"round"}},{"kind":"Field","name":{"kind":"Name","value":"location"}},{"kind":"Field","name":{"kind":"Name","value":"firstOpponent"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"secondOpponent"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]}}]}}]} as unknown as DocumentNode<MyPredictionsQuery, MyPredictionsQueryVariables>;