// This file is auto-generated by scripts/generate-graphql-index.cjs
// Do not edit this file manually

// Export all types from generated types file
export * from '../generated/types';

// Export all generated operations, fragments, and documents
export * from './mutations/AdminCreatePlayer.generated';
export * from './mutations/AdminCreateTeam.generated';
export * from './mutations/AdminLogin.generated';
export * from './mutations/CreateMatch.generated';
export * from './mutations/CreateMatchEvent.generated';
export * from './mutations/CreateNews.generated';
export * from './mutations/DeleteMatch.generated';
export * from './mutations/DeleteMatchEvent.generated';
export * from './mutations/DeleteNews.generated';
export * from './mutations/DeletePlayer.generated';
export * from './mutations/DeleteTeam.generated';
export * from './mutations/LoginUser.generated';
export * from './mutations/UpdateMatch.generated';
export * from './mutations/UpdateNews.generated';
export * from './mutations/UpdatePlayer.generated';
export * from './mutations/UpdateTeam.generated';
export * from './queries/GetNews.generated';
export * from './queries/GetNewsById.generated';
export * from './queries/GetPlayerById.generated';
export * from './queries/GetPlayerStandings.generated';
export * from './queries/GetTeamById.generated';
export * from './queries/GetTeams.generated';
export * from './queries/GetTeamsWithPlayers.generated';
export * from './queries/MatchById.generated';
export * from './queries/MatchEvents.generated';
export * from './queries/Matches.generated';
