// This file is auto-generated by scripts/generate-graphql-index.cjs
// Do not edit this file manually

// Export all types from generated types file
export * from '../generated/types';

// Export all generated operations, fragments, and documents
export * from './mutations/AdminCreatePlayer.generated';
export * from './mutations/AdminCreateTeam.generated';
export * from './mutations/AdminLogin.generated';
export * from './queries/GetNews.generated';
export * from './queries/GetNewsById.generated';
export * from './queries/GetTeams.generated';
