'use client';

import { PlayerPosition } from '@/graphql';
import FantasyViewUi from './FantasyViewUi';
import type { FantasyTeamData, FantasyAvailablePlayer, FantasyPlayer } from './contracts';

const emptyJersey = { color: '#6B7280', textColor: '#FFFFFF', label: '' };

const emptySlot = (id: string, position: PlayerPosition): FantasyPlayer => ({
  id,
  firstName: '',
  lastName: '',
  displayName: '',
  position,
  jersey: emptyJersey,
});

const emptyStarters: FantasyPlayer[] = [
  emptySlot('empty-gk-1', PlayerPosition.Goalkeeper),
  emptySlot('empty-def-1', PlayerPosition.Defender),
  emptySlot('empty-def-2', PlayerPosition.Defender),
  emptySlot('empty-mid-1', PlayerPosition.Midfielder),
  emptySlot('empty-mid-2', PlayerPosition.Midfielder),
  emptySlot('empty-fwd-1', PlayerPosition.Forward),
];

const emptyBench: FantasyPlayer[] = [
  emptySlot('empty-bench-1', PlayerPosition.Defender),
  emptySlot('empty-bench-2', PlayerPosition.Midfielder),
  emptySlot('empty-bench-3', PlayerPosition.Forward),
];

// TODO: Replace with real API data. This mock represents the user's current team.
const mockTeam: FantasyTeamData = {
  teamName: 'Nasko FC',
  latestPoints: 17,
  averagePoints: 37,
  highestPoints: 134,
  freeTransfers: 6,
  gameweek: 1,
  budget: 10,
  transferCost: 0,
  starters: emptyStarters,
  bench: emptyBench,
  initialRemovedPlayerIds: new Set([...emptyStarters, ...emptyBench].map((p) => p.id)),
};

// TODO: Replace with real API data. This mock represents all players available for transfer.
const mockAvailablePlayers: FantasyAvailablePlayer[] = [
  {
    id: 'p1',
    firstName: 'Mohamed',
    lastName: 'Salah',
    displayName: 'M. Salah',
    teamShort: 'LIV',
    position: PlayerPosition.Midfielder,
    price: 13.0,
    points: 156,
  },
  {
    id: 'p2',
    firstName: 'Erling',
    lastName: 'Haaland',
    displayName: 'Haaland',
    teamShort: 'MCI',
    position: PlayerPosition.Forward,
    price: 13.5,
    points: 142,
  },
  {
    id: 'p3',
    firstName: 'Kevin',
    lastName: 'De Bruyne',
    displayName: 'De Bruyne',
    teamShort: 'MCI',
    position: PlayerPosition.Midfielder,
    price: 10.2,
    points: 128,
  },
  {
    id: 'p4',
    firstName: 'Heung-min',
    lastName: 'Son',
    displayName: 'Son Heung-min',
    teamShort: 'TOT',
    position: PlayerPosition.Midfielder,
    price: 9.8,
    points: 112,
  },
  {
    id: 'p5',
    firstName: 'Bukayo',
    lastName: 'Saka',
    displayName: 'B. Saka',
    teamShort: 'ARS',
    position: PlayerPosition.Midfielder,
    price: 9.5,
    points: 108,
  },
  {
    id: 'p6',
    firstName: 'Cole',
    lastName: 'Palmer',
    displayName: 'Palmer',
    teamShort: 'CHE',
    position: PlayerPosition.Midfielder,
    price: 9.2,
    points: 134,
  },
  {
    id: 'p7',
    firstName: 'Virgil',
    lastName: 'van Dijk',
    displayName: 'V. van Dijk',
    teamShort: 'LIV',
    position: PlayerPosition.Defender,
    price: 6.5,
    points: 89,
  },
  {
    id: 'p8',
    firstName: 'Ruben',
    lastName: 'Dias',
    displayName: 'Dias',
    teamShort: 'MCI',
    position: PlayerPosition.Defender,
    price: 6.0,
    points: 78,
  },
  {
    id: 'p9',
    firstName: 'Trent',
    lastName: 'Alexander-Arnold',
    displayName: 'Alexander-Arnold',
    teamShort: 'LIV',
    position: PlayerPosition.Defender,
    price: 7.5,
    points: 95,
  },
  {
    id: 'p10',
    firstName: 'Ollie',
    lastName: 'Watkins',
    displayName: 'Watkins',
    teamShort: 'AVL',
    position: PlayerPosition.Forward,
    price: 8.5,
    points: 98,
  },
  {
    id: 'p11',
    firstName: 'Alexander',
    lastName: 'Isak',
    displayName: 'Isak',
    teamShort: 'NEW',
    position: PlayerPosition.Forward,
    price: 8.8,
    points: 105,
  },
  {
    id: 'p12',
    firstName: 'Manuel',
    lastName: 'Neuer',
    displayName: 'Neuer',
    teamShort: 'BAY',
    position: PlayerPosition.Goalkeeper,
    price: 5.5,
    points: 82,
  },
  {
    id: 'p13',
    firstName: 'Robert',
    lastName: 'Sanchez',
    displayName: 'Sanchez',
    teamShort: 'CHE',
    position: PlayerPosition.Goalkeeper,
    price: 4.9,
    points: 68,
  },
  {
    id: 'p14',
    firstName: 'David',
    lastName: 'Raya',
    displayName: 'Raya',
    teamShort: 'ARS',
    position: PlayerPosition.Goalkeeper,
    price: 5.0,
    points: 85,
  },
  {
    id: 'p15',
    firstName: 'Emiliano',
    lastName: 'Martinez',
    displayName: 'Martinez',
    teamShort: 'AVL',
    position: PlayerPosition.Goalkeeper,
    price: 4.8,
    points: 72,
  },
  {
    id: 'p16',
    firstName: 'William',
    lastName: 'Saliba',
    displayName: 'Saliba',
    teamShort: 'ARS',
    position: PlayerPosition.Defender,
    price: 6.2,
    points: 86,
  },
  {
    id: 'p17',
    firstName: 'John',
    lastName: 'Stones',
    displayName: 'Stones',
    teamShort: 'MCI',
    position: PlayerPosition.Defender,
    price: 5.5,
    points: 62,
  },
  {
    id: 'p18',
    firstName: 'Gabriel',
    lastName: 'Magalhaes',
    displayName: 'Gabriel',
    teamShort: 'ARS',
    position: PlayerPosition.Defender,
    price: 6.0,
    points: 84,
  },
  {
    id: 'p19',
    firstName: 'Jude',
    lastName: 'Bellingham',
    displayName: 'Bellingham',
    teamShort: 'RMA',
    position: PlayerPosition.Midfielder,
    price: 8.5,
    points: 102,
  },
  {
    id: 'p20',
    firstName: 'Martin',
    lastName: 'Odegaard',
    displayName: 'Odegaard',
    teamShort: 'ARS',
    position: PlayerPosition.Midfielder,
    price: 8.0,
    points: 88,
  },
  {
    id: 'p21',
    firstName: 'Declan',
    lastName: 'Rice',
    displayName: 'Rice',
    teamShort: 'ARS',
    position: PlayerPosition.Midfielder,
    price: 6.5,
    points: 76,
  },
  {
    id: 'p22',
    firstName: 'James',
    lastName: 'Maddison',
    displayName: 'Maddison',
    teamShort: 'TOT',
    position: PlayerPosition.Midfielder,
    price: 7.0,
    points: 74,
  },
  {
    id: 'p23',
    firstName: 'Julian',
    lastName: 'Alvarez',
    displayName: 'Alvarez',
    teamShort: 'ATM',
    position: PlayerPosition.Forward,
    price: 7.5,
    points: 68,
  },
  {
    id: 'p24',
    firstName: 'Darwin',
    lastName: 'Nunez',
    displayName: 'Nunez',
    teamShort: 'LIV',
    position: PlayerPosition.Forward,
    price: 7.2,
    points: 58,
  },
  {
    id: 'p25',
    firstName: 'Kai',
    lastName: 'Havertz',
    displayName: 'Havertz',
    teamShort: 'ARS',
    position: PlayerPosition.Forward,
    price: 7.5,
    points: 82,
  },
  {
    id: 'p26',
    firstName: 'Sergio',
    lastName: 'Ramos',
    displayName: 'Ramos',
    teamShort: 'PSG',
    position: PlayerPosition.Defender,
    price: 5.0,
    points: 56,
  },
  {
    id: 'p27',
    firstName: 'Luka',
    lastName: 'Modric',
    displayName: 'Modric',
    teamShort: 'RMA',
    position: PlayerPosition.Midfielder,
    price: 7.8,
    points: 72,
  },
  {
    id: 'p28',
    firstName: 'Lionel',
    lastName: 'Messi',
    displayName: 'Messi',
    teamShort: 'MIA',
    position: PlayerPosition.Forward,
    price: 11.0,
    points: 94,
  },
  {
    id: 'p29',
    firstName: 'Kylian',
    lastName: 'Mbappe',
    displayName: 'Mbappe',
    teamShort: 'RMA',
    position: PlayerPosition.Forward,
    price: 12.0,
    points: 118,
  },
  {
    id: 'p30',
    firstName: 'Vinicius',
    lastName: 'Jr',
    displayName: 'Vinicius Jr',
    teamShort: 'RMA',
    position: PlayerPosition.Forward,
    price: 10.5,
    points: 110,
  },
];

const FantasyView = () => {
  return <FantasyViewUi team={mockTeam} availablePlayers={mockAvailablePlayers} />;
};

export default FantasyView;
